<?php
$seach_arr = array(
	//每个表单控件NAME值作为KEY
	'eiregistername'=>array(
	  'kind'=>'company',   //要搜索的类型，企业搜索固定为company
	  'name'=>'eiregistername',
	  'msg'=>'企业名称',
	  'width'=>'100px',
	  'arr'=>'',
	  'sql_field'=>'zuzhi_id',
	  'sql_kind'=>'in'
	),
	 'htcode'=>array(
	  'kind'=>'htcode',
	  'name'=>'htcode',
	  'msg'=>'合同编号',
	  'width'=>'100px',
	  'arr'=>'',
	  'sql_field'=>'ht_id',
	  'sql_kind'=>'='
	),
	'auditplandate1'=>array(
	  'kind'=>'date1',
	  'name'=>'auditplandate1',
	  'msg'=>'计划开始时间',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'auditplandate',
	  'sql_kind'=>'>='
	),
	  'auditplandate2'=>array(
	  'kind'=>'date2',
	  'name'=>'auditplandate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'auditplandate',
	  'sql_kind'=>'<='
	),
	'iso'=>array(
	  'kind'=>'select',
	  'name'=>'iso',
	  'msg'=>'认证体系',
	  'width'=>'70px',
	  'arr'=>$setup_audit_iso,
	  'sql_field'=>'iso',
	  'sql_kind'=>'='
	),
	'certEnd_date'=>array(
		'kind'=>'text',
		'name'=>'certEnd_date',
		'msg'=>'证书到期提醒',
		'width'=>'40px',
		'arr'=>'',
		'sql_field'=>'',
		'sql_kind'=>''
	),
	'audit_date'=>array(
		'kind'=>'text',
		'name'=>'audit_date',
		'msg'=>'二阶段审核提醒',
		'width'=>'40px',
		'arr'=>'',
		'sql_field'=>'',
		'sql_kind'=>''
	),
	'br1'=>array(
	'kind'=>'br'
	),
	'htxmcode'=>array(
		'kind'=>'htxmcode',
		'name'=>'htxmcode',
		'msg'=>'项目编号',
		'width'=>'100px',
		'arr'=>'',
		'sql_field'=>'htxm_id',
		'sql_kind'=>'in'
	  ),

	'htfrom'=>array(
	  'kind'=>'select',   //要搜索的类型
	  'name'=>'htfrom',
	  'msg'=>'合同来源',
	  'width'=>'104px',
	  'arr'=>$setup_htfrom,
	  'sql_field'=>'htfrom',
	  'sql_kind'=>'='
	),
	'finalItemDate1'=>array(
	  'kind'=>'date1',
	  'name'=>'finalItemDate1',
	  'msg'=>'监查最后时间',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'finalItemDate',
	  'sql_kind'=>'>='
	),
	  'finalItemDate2'=>array(
	  'kind'=>'date2',
	  'name'=>'finalItemDate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'finalItemDate',
	  'sql_kind'=>'<='
	),
	'audit_type'=>array(
	  'kind'=>'select',
	  'name'=>'audit_type',
	  'msg'=>'审核类型',
	  'width'=>'70px',
	  'arr'=>$setup_audit_type,
	  'sql_field'=>'audit_type',
	  'sql_kind'=>'='
	),
	'cw_online'=>array(
	  'kind'=>'select',
	  'name'=>'cw_online',
	  'msg'=>'是否到款',
	  'width'=>'40px',
	  'arr'=>array('1'=>'是','0'=>'否'),
	  'sql_field'=>'cw_online',
	  'sql_kind'=>'='
	),
	'product'=>array(
		'kind'=>'text',
		'name'=>'product',
		'msg'=>'认证产品',
		'width'=>'100px',
		'arr'=>'',
		'sql_field'=>'',
		'sql_kind'=>''
	)
);
?>
