<?php
$seach_arr=array(
	'username'=>array(
		'kind'=>'text',
		'name'=>'username',
		'msg'=>'姓名',
		'width'=>'100px',
		'arr'=>'',
		'sql_field'=>'username',
		'sql_kind'=>'%like%'
	  ),
	  'province'=>array(
	  'kind'=>'select',   //?????company
	  'name'=>'province',
	  'msg'=>'地区',
	  'width'=>'100px',
	  'arr'=>$setup_province,
	  'sql_field'=>'province',
	  'sql_kind'=>'='
	),
	't_date'=>array(
		'kind'=>'t_date',
		'name'=>'t_date',
		'msg'=>'提前提醒',
		'width'=>'100px',
		'arr'=>'',
		'sql_field'=>'pinyongover',
		'sql_kind'=>'<='
	),
	'date1'=>array(
		'kind'=>'date1',
		'name'=>'date1',
		'msg'=>'出生日期',
		'width'=>'90px',
		'arr'=>'',
		'sql_field'=>'birthday',
		'sql_kind'=>'>='
	 ),
	'date2'=>array(
		'kind'=>'date2',
		'name'=>'date2',
		'msg'=>'',
		'width'=>'90px',
		'arr'=>'',
		'sql_field'=>'birthday',
		'sql_kind'=>'<='
	 ),
		'br'=>array(
	    'kind'=>'br'
	 ),
    'htfrom'=>array(
	  'kind'=>'select',   
	  'name'=>'htfrom',
	  'msg'=>'人员来源',
	  'width'=>'100px',
	  'arr'=>$setup_htfrom,
	  'sql_field'=>'htfrom',
	  'sql_kind'=>'='
	),
    'worktype'=>array(
	  'kind'=>'select',   
	  'name'=>'worktype',
	  'msg'=>'审核员性质',
	  'width'=>'100px',
	  'arr'=>array('01'=>'兼职','02'=>'专职','08'=>'其他'),
	  'sql_field'=>'worktype',
	  'sql_kind'=>'='
	),
    'working'=>array(
	  'kind'=>'select',   
	  'name'=>'working',
	  'msg'=>'合同状态',
	  'width'=>'100px',
	  'arr'=>array('1'=>'正常','0'=>'解聘','2'=>'停用'),
	  'sql_field'=>'working',
	  'sql_kind'=>'='
	),
	'xueli'=>array(
	  'kind'=>'select',   
	  'name'=>'xueli',
	  'msg'=>'学历',
	  'width'=>'100px',
	  'arr'=>$setup_hr_education,
	  'sql_field'=>'xueli',
	  'sql_kind'=>''
	),
);
?>
