<?php
$seach_arr = array(
		'htxmcode'=>array(
		'kind'=>'htxmcode',
		'name'=>'htxmcode',
		'msg'=>'项目编号',
		'width'=>'100px',
		'arr'=>'',
		'sql_field'=>'htxm_id',
		'sql_kind'=>'in'
	),
	'username'=>array(
	  'kind'=>'text',   //要搜索的类型，企业搜索固定为company
	  'name'=>'username',
	  'msg'=>'评定人名',
	  'width'=>'90px',
	  'arr'=>'',
	  'sql_field'=>'username',
	  'sql_kind'=>'='
	),
	'thendate1'=>array(
	  'kind'=>'date1',
	  'name'=>'thendate1',
	  'msg'=>'接卷日期',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'thendate',
	  'sql_kind'=>'>='
	),
	  'thendate2'=>array(
	  'kind'=>'date2',
	  'name'=>'thendate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'thendate',
	  'sql_kind'=>'<='
	),

	'iso'=>array(
	  'kind'=>'select',
	  'name'=>'iso',
	  'msg'=>'体系',
	  'width'=>'104px',
	  'arr'=>$setup_audit_iso,
	  'sql_field'=>'iso',
	  'sql_kind'=>'='
	),
	'br1'=>array(
	'kind'=>'br'
	),
		'eiregistername'=>array(
	  'kind'=>'company',   //要搜索的类型，企业搜索固定为company
	  'name'=>'eiregistername',
	  'msg'=>'企业名称',
	  'width'=>'100px',
	  'arr'=>'',
	  'sql_field'=>'zuzhi_id',
	  'sql_kind'=>'in'
	),

	'htcode'=>array(
	  'kind'=>'htcode',
	  'name'=>'htcode',
	  'msg'=>'合同编号',
	  'width'=>'90px',
	  'arr'=>'',
	  'sql_field'=>'ht_id',
	  'sql_kind'=>'='
	),

	'rossdate1'=>array(
	  'kind'=>'date1',
	  'name'=>'rossdate1',
	  'msg'=>'交卷时间',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'rossdate',
	  'sql_kind'=>'>='
	),
	  'rossdate2'=>array(
	  'kind'=>'date2',
	  'name'=>'rossdate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'rossdate',
	  'sql_kind'=>'<='
	),
	'approvaldate1'=>array(
	  'kind'=>'date1',
	  'name'=>'approvaldate1',
	  'msg'=>'评定通过时间',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'approvaldate',
	  'sql_kind'=>''
	),
	  'approvaldate2'=>array(
	  'kind'=>'date2',
	  'name'=>'approvaldate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'approvaldate',
	  'sql_kind'=>''
	),
);
?>
