<?php
$seach_arr = array(
	//每个表单控件NAME值作为KEY
	'eiregistername'=>array(
	  'kind'=>'company',   //要搜索的类型，企业搜索固定为company
	  'name'=>'eiregistername',
	  'msg'=>'企业名称',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'zuzhi_id',
	  'sql_kind'=>'in'
	),
	'audit_type'=>array(
	  'kind'=>'select',
	  'name'=>'audit_type',
	  'msg'=>'审核类型',
	  'width'=>'74px',
	  'arr'=>$setup_audit_type,
	  'sql_field'=>'audit_type',
	  'sql_kind'=>'='
	),
	'taskBeginDate1'=>array(
	  'kind'=>'date1',
	  'name'=>'taskBeginDate1',
	  'msg'=>'审核开始日期',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'taskBeginDate',
	  'sql_kind'=>''
	),
	  'taskBeginDate2'=>array(
	  'kind'=>'date2',
	  'name'=>'taskBeginDate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'taskBeginDate',
	  'sql_kind'=>''
	),
	'zl_okdate1'=>array(
	  'kind'=>'date1',
	  'name'=>'zl_okdate1',
	  'msg'=>'资料收回日期',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'zl_okdate',
	  'sql_kind'=>''
	),
	  'zl_okdate2'=>array(
	  'kind'=>'date2',
	  'name'=>'zl_okdate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'zl_okdate',
	  'sql_kind'=>''
	),
		'to_assess_date1'=>array(
	  'kind'=>'date1',
	  'name'=>'to_assess_date1',
	  'msg'=>'转技委会日期',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'to_assess_date',
	  'sql_kind'=>'>='
	),
	  'to_assess_date2'=>array(
	  'kind'=>'date2',
	  'name'=>'to_assess_date2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'to_assess_date',
	  'sql_kind'=>'<='
	),
	'br1'=>array(
	'kind'=>'br'
	),
	'htxmcode'=>array(
		'kind'=>'htxmcode',
		'name'=>'htxmcode',
		'msg'=>'项目编号',
		'width'=>'70px',
		'arr'=>'',
		'sql_field'=>'htxm_id',
		'sql_kind'=>'in'
	),
	'htcode'=>array(
	  'kind'=>'htcode',
	  'name'=>'htcode',
	  'msg'=>'合同编号',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'ht_id',
	  'sql_kind'=>'='
	),

	'iso'=>array(
	  'kind'=>'select',
	  'name'=>'iso',
	  'msg'=>'认证体系',
	  'width'=>'74px',
	  'arr'=>$setup_audit_iso,
	  'sql_field'=>'iso',
	  'sql_kind'=>'='
	),
	  'taskEndDate1'=>array(
	  'kind'=>'date1',
	  'name'=>'taskEndDate1',
	  'msg'=>'审核结束日期',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'taskEndDate',
	  'sql_kind'=>''
	),
	  'taskEndDate2'=>array(
	  'kind'=>'date2',
	  'name'=>'taskEndDate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'taskEndDate',
	  'sql_kind'=>''
	),
	'htfrom'=>array(
	  'kind'=>'select',   //要搜索的类型
	  'name'=>'htfrom',
	  'msg'=>'合同来源',
	  'width'=>'104px',
	  'arr'=>$setup_htfrom,
	  'sql_field'=>'htfrom',
	  'sql_kind'=>'='
	),
	'renzhengfanwei'=>array(
		'kind'=>'text',
		'name'=>'renzhengfanwei',
		'msg'=>'产品范围',
		'width'=>'100px',
		'arr'=>'',
		'sql_field'=>'product',
		'sql_kind'=>'%like%'
	),
);
?>