<?php
$seach_arr = array(
	//每个表单控件NAME值作为KEY
	'eiregistername'=>array(
	  'kind'=>'company',   //要搜索的类型，企业搜索固定为company
	  'name'=>'eiregistername',
	  'msg'=>'企业名称',
	  'width'=>'100px',
	  'arr'=>'',
	  'sql_field'=>'zuzhi_id',
	  'sql_kind'=>'in'
	),
	'approvaldate1'=>array(
	  'kind'=>'date1',
	  'name'=>'approvaldate1',
	  'msg'=>'评定通过时间',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'approvaldate',
	  'sql_kind'=>'>='
	),
	  'approvaldate2'=>array(
	  'kind'=>'date2',
	  'name'=>'approvaldate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'approvaldate',
	  'sql_kind'=>'<='
	),
	'ifchangecert'=>array(
	  'kind'=>'select',   //要搜索的类型
	  'name'=>'ifchangecert',
	  'msg'=>'换证',
	  'width'=>'40px',
	  'arr'=>array('1'=>'是','0'=>'否'),
	  'sql_field'=>'ifchangecert',
	  'sql_kind'=>'='
	),
	'htfrom'=>array(
	  'kind'=>'select',   //要搜索的类型
	  'name'=>'htfrom',
	  'msg'=>'合同来源',
	  'width'=>'80px',
	  'arr'=>$setup_htfrom,
	  'sql_field'=>'htfrom',
	  'sql_kind'=>'='
	),
	'iso'=>array(
	  'kind'=>'select',
	  'name'=>'iso',
	  'msg'=>'体系',
	  'width'=>'70px',
	  'arr'=>$setup_audit_iso,
	  'sql_field'=>'iso',
	  'sql_kind'=>'='
	),
	'zs_if'=>array(
	  'kind'=>'select',
	  'name'=>'zs_if',
	  'msg'=>'评定结论',
	  'width'=>'80px',
	  'arr'=>$setup_pd_online,
	  'sql_field'=>'zs_if',
	  'sql_kind'=>'='
	),
	'renzhengfanwei'=>array(
	'kind'=>'text',
	'name'=>'renzhengfanwei',
	'msg'=>'产品范围',
	'width'=>'100px',
	'arr'=>'',
	'sql_field'=>'renzhengfanwei',
	'sql_kind'=>'%like%'
  ),
	'br1'=>array(
	'kind'=>'br'
	),
	'htxmcode'=>array(
		'kind'=>'htxmcode',
		'name'=>'htxmcode',
		'msg'=>'项目编号',
		'width'=>'100px',
		'arr'=>'',
		'sql_field'=>'htxm_id',
		'sql_kind'=>'in'
	),
	 'htcode'=>array(
	  'kind'=>'htcode',
	  'name'=>'htcode',
	  'msg'=>'合同编号',
	  'width'=>'100px',
	  'arr'=>'',
	  'sql_field'=>'ht_id',
	  'sql_kind'=>'='
	),
	  'zl_okdate1'=>array(
	  'kind'=>'date1',
	  'name'=>'zl_okdate1',
	  'msg'=>'资料回收时间',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'zl_okdate',
	  'sql_kind'=>''
	),
	  'zl_okdate2'=>array(
	  'kind'=>'date2',
	  'name'=>'zl_okdate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'zl_okdate',
	  'sql_kind'=>''
	),
	'taskBeginDate1'=>array(
	  'kind'=>'date1',
	  'name'=>'taskBeginDate1',
	  'msg'=>'审核开始时间',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'taskBeginDate',
	  'sql_kind'=>''
	),
	  'taskBeginDate2'=>array(
	  'kind'=>'date2',
	  'name'=>'taskBeginDate2',
	  'msg'=>'',
	  'width'=>'70px',
	  'arr'=>'',
	  'sql_field'=>'taskBeginDate',
	  'sql_kind'=>''
	),
	  'xmonline'=>array(
	  'kind'=>'hidden',
	  'name'=>'xmonline',
	  'msg'=>'',
	  'width'=>'',
	  'arr'=>'',
	  'sql_field'=>'xmonline',
	  'sql_kind'=>'='
	),
	'audit_type'=>array(
	  'kind'=>'select',
	  'name'=>'audit_type',
	  'msg'=>'审核类型',
	  'width'=>'80px',
	  'arr'=>$setup_audit_type,
	  'sql_field'=>'audit_type',
	  'sql_kind'=>'='
	)
);
?>
